### ISSUE TITLE
The geoservices provider is not supported

### ISSUE THREAD

**Issue by 4kProgrammer** [Mud-Player/MudMap#1]
when I run this project and set my offline directory this message showed in output section of QT creator.

1 ,  "The geoservices provider is not supported."
qml: [object Object]
qrc:/main.qml:19:9: Unable to assign [undefined] to QDeclarativeGeoMapType*

**Comment by Mud-Player** [comment]
Did you copy the 'geoservices' directory to the path where exe binary running? if not, try it.

**Comment by Mud-Player** [comment]
> when I run this project and set my offline directory this message showed in output section of QT creator.
> 
> 1 , "The geoservices provider is not supported."
> qml: [object Object]
> qrc:/main.qml:19:9: Unable to assign [undefined] to QDeclarativeGeoMapType*

**Comment by 4kProgrammer** [comment]
In build Directory exist these files

C:\Users\...\Desktop\MudMap-master\build-MudMap-Desktop_Qt_5_14_0_MinGW_32_bit-Debug\plugins\geoservices

libqtgeoservices_mud.a
qtgeoservices_mud.dll
qtgeoservices_mud.dll.debug

**Comment by 4kProgrammer** [comment]
I test this project whit QT 5.14 and 5.12

**Comment by Mud-Player** [comment]
> I test this project whit QT 5.14 and 5.12

Copy the entire geoservices folder to exe's directory

**Comment by 4kProgrammer** [comment]
Where are the files stored? i Copied these file from "C:\Users...\Desktop\MudMap-master\build-MudMap-Desktop_Qt_5_14_0_MinGW_32_bit-Debug\plugins\geoservices" to "C:\Users...\Desktop\MudMap-master\build-MudMap-Desktop_Qt_5_14_0_MinGW_32_bit-Debug\" and press F5 in QT creator

**Comment by Mud-Player** [comment]
> Where are the files stored? i Copied these file from "C:\Users...\Desktop\MudMap-master\build-MudMap-Desktop_Qt_5_14_0_MinGW_32_bit-Debug\plugins\geoservices" to "C:\Users...\Desktop\MudMap-master\build-MudMap-Desktop_Qt_5_14_0_MinGW_32_bit-Debug" and press F5 in QT creator

The project MudViewer's output path.

**Comment by 4kProgrammer** [comment]
Could you please share with me the build directory of this project as well, perhaps this way I can understand where I have a mistake?

**Comment by Mud-Player** [comment]
> Could you please share with me the build directory of this project as well, perhaps this way I can understand where I have a mistake?

Build directory as follows:
-.qmake.stash
-lib/
-Makefile
-mkspecs/
-MudPlugin/
-MudViewer/
-plugins/

TODO: Copy plugins\geoservices to MudViewer\debug.
